<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>uninstall</AssemblyName>
    <RootNamespace>SoundboySetup</RootNamespace>
    <ApplicationIcon>..\..\SOUNDBOY\app.ico</ApplicationIcon>
    <ApplicationManifest>..\Shared\app.manifest</ApplicationManifest>
    <Version>2.1.0</Version>
    <Product>SOUNDBOY</Product>
    <AssemblyTitle>SOUNDBOY Uninstaller</AssemblyTitle>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\*.cs" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
</Project>
